### ISSUE TITLE
[Feature Request] One less .js or dotfile in directory

### ISSUE THREAD

**Issue by tabrindle** [tjbenton/docs#11]
Rather than requiring a docsfile.js or .docsfile, add ability to add a docs object to package.json for configuration. Babel, Ava, and others all have this ability.

**Comment by tjbenton** [comment]
This may be available already, or I may be thinking of a different project I worked on around the same time.

**Comment by tjbenton** [comment]
Just confirmed this is already available. You can place the config under the `package.json` under the `docs` key
